SESSION_NAME=BQB2gJ8sl3BlYF9HNz2D3xwFUXzxd7g76JUtWArBextb40IPmecS7FFE3emY6-xs6DU-kYJnCiQkORtD1oVftQayZhvocwqsAdNDPaLXda6ctKrfglYhgcksn6dxlF-hVyDkmNUz69CK4LreQdXgLz3cQxSRzhiS-ugG7xKA6y9JX_2n-jzJ3NgEd8g8sycfOfUqd_FFmj9LimnXRFk471WQlVPCbwYj-kJjK1KIY1vA6kXPaJ1bpoemV0FaTmnxThMx96K4rK_iN_kKyG0Iptuugs_Cq6P3WzUC_W8rFxzR97hOu88RIOMBRzHRwxaFYrR2eSjf6BG8VLwsvrq7i9hPazKisgA # If you don't deploy with docker, keep it as is and if you do so it should be a session string generated by "python str.py"
BOT_TOKEN=1829168270:AAEUOTVyuqWkMO8MQJiiBtMIS4fmCsnDPSw
BOT_NAME=HELLBOT
API_ID=5986019
API_HASH=88da58a3fe72e5077a63c828d0705e73
SUDO_USERS=1480007084 # List of user IDs separated by space
DURATION_LIMIT=10 # in minutes (default: 7)
ARQ_API_KEY=PHIZVQ-LUPPJF-UPJEXL-KELUKW-ARQ
UPDATES_CHANNEL=DaisyXupdates
BG_IMAGE=https://telegra.ph//file/b0a278873d9106e76e619.png

 
